import { describe, test, expect } from "bun:test"
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { writeClientOutputs } from "../src/client-generator/index.ts"
import type { ResolvedPluginOptions } from "../src/options.ts"
import type { ResolvedConfig } from "vite"

const mockConfig = (root: string): ResolvedConfig =>
  ({ root, command: "serve", build: { outDir: "dist" } } as any)

const mockOptions = (overrides: Partial<ResolvedPluginOptions> = {}): ResolvedPluginOptions =>
  ({
    entries: [],
    clientPath: "src/effect-client.ts",
    dts: "src/effect-client.d.ts",
    virtualModuleId: "virtual:effect/client",
    resolvedVirtualModuleId: "\0virtual:effect/client",
    virtualTypesModuleId: "virtual:effect/client?types",
    resolvedVirtualTypesModuleId: "\0virtual:effect/client?types",
    clientKind: "promise",
    ...overrides,
  } as any)

describe("writeClientOutputs", () => {
  test("writes client file to disk", async () => {
    const root = await mkdtemp(join(tmpdir(), "vpe-"))
    try {
      const options = mockOptions({ clientPath: "src/effect-client.ts" })
      const config = mockConfig(root)
      await writeClientOutputs(options, config)
      const content = await readFile(join(root, "src/effect-client.ts"), "utf8")
      expect(content).toContain("Auto-generated by vite-plugin-effect")
      expect(content).toContain("export const client")
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })

  test("writes dts file to disk", async () => {
    const root = await mkdtemp(join(tmpdir(), "vpe-"))
    try {
      const options = mockOptions({ dts: "types/client.d.ts" })
      const config = mockConfig(root)
      await writeClientOutputs(options, config)
      const content = await readFile(join(root, "types/client.d.ts"), "utf8")
      expect(content).toContain("declare module")
      expect(content).toContain("EffectClientConfig")
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })

  test("skips client write when clientPath is false", async () => {
    const root = await mkdtemp(join(tmpdir(), "vpe-"))
    try {
      const options = mockOptions({ clientPath: false, dts: false })
      const config = mockConfig(root)
      await writeClientOutputs(options, config)
      // Should not throw
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })
})
