import { describe, test, expect } from "bun:test"
import {
  generateVirtualClientModule,
  generateVirtualTypesModule,
  generateClientOutputs,
} from "../src/client-generator/index.ts"
import type { ResolvedPluginOptions, ResolvedClientEntry } from "../src/options.ts"
import type { ResolvedConfig } from "vite"

const mockConfig = (root: string = "/tmp") =>
  ({ root } as ResolvedConfig)

const mockOptions = (overrides: Partial<ResolvedPluginOptions> = {}): ResolvedPluginOptions =>
  ({
    entries: [],
    clientPath: "src/effect-client.ts",
    dts: "src/effect-client.d.ts",
    virtualModuleId: "virtual:effect/client",
    resolvedVirtualModuleId: "\0virtual:effect/client",
    virtualTypesModuleId: "virtual:effect/client-types",
    resolvedVirtualTypesModuleId: "\0virtual:effect/client-types",
    clientKind: "promise",
    ...overrides,
  } as any)

describe("client-generator", () => {
  describe("generateVirtualClientModule", () => {
    test("returns custom virtual module content when provided", () => {
      const options = mockOptions({
        virtualModuleContent: ({ entry }) => `import { custom } from "${entry.sharedPath}"`,
        entries: [{ sharedPath: "./src/shared.ts" } as ResolvedClientEntry],
      })
      const code = generateVirtualClientModule(options, mockConfig())
      expect(code).toContain("import { custom } from \"./src/shared.ts\"")
    })

    test("throws when clientPath is false and no virtualModuleContent", () => {
      const options = mockOptions({ clientPath: false })
      expect(() => generateVirtualClientModule(options, mockConfig())).toThrow("clientPath: false requires virtualModuleContent")
    })

    test("returns default re-export for clientPath", () => {
      const options = mockOptions({ clientPath: "src/effect-client.ts" })
      const code = generateVirtualClientModule(options, mockConfig("/project"))
      expect(code).toContain("export { client, effectClient, promiseClient }")
      expect(code).toContain("/project/src/effect-client.ts")
    })
  })

  describe("generateVirtualTypesModule", () => {
    test("returns virtual client types", () => {
      const code = generateVirtualTypesModule()
      expect(code).toContain("AwaitableClient")
      expect(code).toContain("effectClient: unknown")
      expect(code).toContain("promiseClient: unknown")
      expect(code).toContain("client: unknown")
    })
  })

  describe("generateClientOutputs", () => {
    test("generates client code with no entries", async () => {
      const options = mockOptions({ entries: [] })
      const config = mockConfig("/tmp")
      const outputs = await generateClientOutputs(options, config)
      expect(outputs.clientCode).toContain("Auto-generated by vite-plugin-effect")
      expect(outputs.dtsCode).toContain("declare module")
    })

    test("generates client code for http entry", async () => {
      const options = mockOptions({
        entries: [{
          type: "http",
          name: "api",
          sharedPath: "./src/shared.ts",
          exportName: "MyApi",
          apiPrefix: "/api",
          rpcPath: "",
        } as ResolvedClientEntry],
      })
      const config = mockConfig("/tmp")
      const outputs = await generateClientOutputs(options, config)
      expect(outputs.clientCode).toContain("MyApi")
      expect(outputs.clientCode).toContain("EffectHttpApiClient")
      expect(outputs.dtsCode).toContain("declare module")
    })

    test("generates client code for rpc entry", async () => {
      const options = mockOptions({
        entries: [{
          type: "rpc",
          name: "rpc",
          sharedPath: "./src/shared.ts",
          exportName: "MyRpc",
          apiPrefix: "",
          rpcPath: "/rpc",
        } as ResolvedClientEntry],
      })
      const config = mockConfig("/tmp")
      const outputs = await generateClientOutputs(options, config)
      expect(outputs.clientCode).toContain("MyRpc")
      expect(outputs.clientCode).toContain("EffectRpcClient")
      expect(outputs.dtsCode).toContain("declare module")
    })
  })
})
