/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
import { HttpApi, HttpApiEndpoint, HttpApiGroup, HttpApiClient } from "effect/unstable/httpapi"
import { Effect, Schema } from "effect"
import { FetchHttpClient } from "effect/unstable/http"
import type { AwaitableClient, MethodInput, MethodPayload, MethodSuccess } from "vite-plugin-effect/client"

const Todo = Schema.Struct({ "id": Schema.Number, "title": Schema.String, "completed": Schema.Boolean }).annotate({ "identifier": "Todo" })

export type Todo = Schema.Schema.Type<typeof Todo>

const __httpApi0 = HttpApi.make("MyApi").add(
  HttpApiGroup.make("todos").add(
    HttpApiEndpoint.make("GET")("getTodos", "/todos", { success: Schema.Array(Todo) })
  )
)

const __effectClient0 = await Effect.runPromise(
  HttpApiClient.make(__httpApi0, { baseUrl: "/api" }).pipe(
    Effect.provide(FetchHttpClient.layer)
  )
)

const reservedRequestKeys = new Set<PropertyKey>(["payload", "params", "query", "headers", "responseMode"])

function normalizeRequest<Request>(request: Request | MethodPayload<Request>, hasArgument: boolean): Request {
  if (!hasArgument) {
    return undefined as Request
  }
  if (request === null || typeof request !== "object") {
    return { payload: request } as Request
  }
  for (const key of reservedRequestKeys) {
    if (key in request) return request as Request
  }
  return { payload: request } as Request
}

export type Entry0EffectClient = HttpApiClient.ForApi<typeof __httpApi0>
export type Entry0PromiseClient = AwaitableClient<Entry0EffectClient>
export type ApiEffectClient = Entry0EffectClient
export type ApiPromiseClient = Entry0PromiseClient
export type ApiClient = Entry0PromiseClient

export namespace Api {
  export namespace todos {
    export namespace getTodos {
      type Method = Entry0EffectClient["todos"]["getTodos"]
      export type Input = MethodInput<Method>
      export type Success = MethodSuccess<Method>
    }
  }
}

export type EffectClient = Entry0EffectClient
export type PromiseClient = Entry0PromiseClient
export type Client = PromiseClient

const __promiseClient0: Entry0PromiseClient = {
  todos: {
    getTodos: (...args) => Effect.runPromise(__effectClient0.todos.getTodos(normalizeRequest<MethodInput<Entry0EffectClient["todos"]["getTodos"]>>(args[0], args.length > 0)))
  }
}

export const effectClient: EffectClient = __effectClient0
export const promiseClient: PromiseClient = __promiseClient0
export const client: Client = __promiseClient0