/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
declare module "vite-plugin-effect/client" {
  interface EffectClientConfig {
    readonly client: import("./effect-client").EffectClient
    readonly defaultClient: import("./effect-client").Client
  }
}

declare module "virtual:effect/client" {
  export { client, effectClient, promiseClient } from "./effect-client"
  export type * from "./effect-client"
}
