import * as path from "node:path"
import type { ResolvedConfig } from "vite"
import { defaultApiPrefix } from "../defaults"
import type { ResolvedClientEntry, ResolvedPluginOptions } from "../options"
import { toRelativeTypeImport } from "../path-utils"
import {
  typeApplication,
  typeAlias,
  entryValueName,
  entryConstName,
  entryTypeName,
  toPascalIdentifier,
  type SchemaExport,
  lt,
} from "./codegen-utils"
import { stripTypeScriptExtension } from "./schema-discovery"

export const generateClientFile = (
  options: ResolvedPluginOptions,
  config: ResolvedConfig,
  clientPath = path.resolve(config.root, options.clientPath || "src/effect-client.ts"),
  schemaExports: ReadonlyArray<SchemaExport> = []
): string => {
  const hasHttpEntries = options.entries.some((entry) => entry.type === "http")
  const hasRpcEntries = options.entries.some((entry) => entry.type === "rpc")
  const imports = options.entries
    .map((entry, index) => {
      const specifier = stripTypeScriptExtension(
        toRelativeTypeImport(config, clientPath, entry.sharedPath)
      )
      return `import { ${entry.exportName} as ${entryValueName(index)} } from ${JSON.stringify(specifier)}`
    })
    .join("\n")

  const entryBlocks = options.entries
    .map((entry, index) => generateEntryBlock(entry, index))
    .join("\n")

  const single = options.entries.length === 1
  const effectClientExpression = single
    ? `${entryConstName(0)}EffectClient`
    : `{ ${options.entries.map((entry, index) => `${entry.name}: ${entryConstName(index)}EffectClient`).join(", ")} }`
  const promiseClientExpression = single
    ? `${entryConstName(0)}PromiseClient`
    : `{ ${options.entries.map((entry, index) => `${entry.name}: ${entryConstName(index)}PromiseClient`).join(", ")} }`
  const clientType = options.clientKind === "effect" ? "EffectClient" : "PromiseClient"
  const clientExpression = options.clientKind === "effect" ? "effectClient" : "promiseClient"
  const schemaTypeAliases = generateSchemaTypeAliases(schemaExports)

  return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
import { Effect${hasRpcEntries ? ", Scope" : ""} } from "effect"
import { FetchHttpClient } from "effect/unstable/http"
${hasHttpEntries ? `import { HttpApi, HttpApiClient as EffectHttpApiClient } from "effect/unstable/httpapi"
import type { HttpApiClient as EffectHttpApiClientTypes } from "effect/unstable/httpapi"` : ""}
${hasRpcEntries ? `import { RpcClient as EffectRpcClient, RpcSerialization } from "effect/unstable/rpc"
import type { RpcClient as EffectRpcClientTypes, RpcClientError as EffectRpcClientError } from "effect/unstable/rpc"` : ""}
import type { AwaitableClient, ClientMethod, MethodInput, MethodPayload, MethodResult } from "vite-plugin-effect/client"
${imports}

const reservedRequestKeys = new Set(["payload", "params", "query", "headers", "responseMode"])

function normalizeRequest(request: unknown): unknown {
  if (request === undefined || request === null || typeof request !== "object") {
    return { payload: request }
  }
  for (const key of reservedRequestKeys) {
    if (key in request) return request
  }
  return { payload: request }
}

${hasHttpEntries ? `
function makeHttpPromiseClient(
  api: HttpApi.AnyWithProps,
  effectClientValue: unknown
): unknown {
  const promiseClientValue: Record<PropertyKey, any> = {}
  HttpApi.reflect(api, {
    onGroup({ group }) {
      if (!group.topLevel) {
        promiseClientValue[group.identifier] = {}
      }
    },
    onEndpoint({ group, endpoint }) {
      const effectContainer = group.topLevel
        ? effectClientValue as Record<PropertyKey, any>
        : (effectClientValue as Record<PropertyKey, any>)[group.identifier]
      const promiseContainer = group.topLevel
        ? promiseClientValue
        : promiseClientValue[group.identifier]
      promiseContainer[endpoint.name] = function(request: unknown) {
        return Effect.runPromise(effectContainer[endpoint.name](normalizeRequest(request)))
      }
    },
  })
  return promiseClientValue
}
` : ""}

${hasRpcEntries ? `
function makeRpcPromiseClient(
  group: { readonly requests: ReadonlyMap<string, unknown> },
  effectClientValue: unknown
): unknown {
  const promiseClientValue: Record<string, unknown> = {}
  for (const tag of group.requests.keys()) {
    promiseClientValue[tag] = function(payload: unknown, options?: unknown) {
      const result = (effectClientValue as Record<string, any>)[tag](payload, options)
      return Effect.isEffect(result)
        ? Effect.runPromise(result as Effect.Effect<unknown, unknown, never>)
        : result
    }
  }
  return promiseClientValue
}
` : ""}

${entryBlocks}

export type EffectClient = ${generateCombinedType(options, "Effect")}
export type PromiseClient = ${generateCombinedType(options, "Promise")}
export type Client = ${clientType}

export type SchemaType<SchemaValue> = SchemaValue extends { readonly Type: infer Type } ? Type : never
${schemaTypeAliases}

export type EntryResultMap<Entry> = {
  readonly [Key in keyof Entry]: Entry[Key] extends ClientMethod
    ? MethodResult<Entry[Key]>
    : Entry[Key] extends object
      ? {
          readonly [Endpoint in keyof Entry[Key]]: Entry[Key][Endpoint] extends ClientMethod
            ? MethodResult<Entry[Key][Endpoint]>
            : never
        }
      : never
}
export type EntryInputMap<Entry> = {
  readonly [Key in keyof Entry]: Entry[Key] extends ClientMethod
    ? MethodInput<Entry[Key]>
    : Entry[Key] extends object
      ? {
          readonly [Endpoint in keyof Entry[Key]]: Entry[Key][Endpoint] extends ClientMethod
            ? MethodInput<Entry[Key][Endpoint]>
            : never
        }
      : never
}
export type EntryPayloadMap<Entry> = {
  readonly [Key in keyof Entry]: Entry[Key] extends ClientMethod
    ? MethodPayload<MethodInput<Entry[Key]>>
    : Entry[Key] extends object
      ? {
          readonly [Endpoint in keyof Entry[Key]]: Entry[Key][Endpoint] extends ClientMethod
            ? MethodPayload<MethodInput<Entry[Key][Endpoint]>>
            : never
        }
      : never
}
export type ClientResults = EntryResultMap<Client>
export type ClientInputs = EntryInputMap<Client>
export type ClientPayloads = EntryPayloadMap<Client>

export type ClientGroups = {
  readonly [Key in keyof Client as Client[Key] extends ClientMethod ? never : Key]: Client[Key]
}
export type ClientGroupName = keyof ClientGroups
${typeAlias("ClientGroup", "Name extends ClientGroupName", "ClientGroups[Name]")}
export type ClientTopLevelEndpointName = {
  readonly [Key in keyof Client]: Client[Key] extends ClientMethod ? Key : never
}[keyof Client]
${typeAlias("ClientEndpointName", "Group extends ClientGroupName", "keyof ClientGroups[Group]")}
${typeAlias(
    "ClientEndpoint",
    "Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>",
    "ClientGroups[Group][Endpoint] extends ClientMethod ? ClientGroups[Group][Endpoint] : never"
  )}
${typeAlias(
    "TopLevelEndpoint",
    "Name extends ClientTopLevelEndpointName",
    "Client[Name] extends ClientMethod ? Client[Name] : never"
  )}
${typeAlias(
    "EndpointInput",
    "Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>",
    "MethodInput<ClientEndpoint<Group, Endpoint>>"
  )}
${typeAlias(
    "EndpointPayload",
    "Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>",
    "MethodPayload<EndpointInput<Group, Endpoint>>"
  )}
${typeAlias(
    "EndpointResult",
    "Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>",
    "MethodResult<ClientEndpoint<Group, Endpoint>>"
  )}

export const effectClient: EffectClient = ${effectClientExpression}
export const promiseClient: PromiseClient = ${promiseClientExpression}
export const client: Client = ${clientExpression}
`
}

const generateSchemaTypeAliases = (schemaExports: ReadonlyArray<SchemaExport>): string => {
  if (schemaExports.length === 0) return ""
  return schemaExports
    .map((schema) =>
      `export type ${schema.name} = ${typeApplication(
        "SchemaType",
        `typeof import(${JSON.stringify(schema.specifier)}).${schema.name}`
      )}`
    )
    .join("\n")
}

const generateEntryBlock = (entry: ResolvedClientEntry, index: number): string => {
  const valueName = entryValueName(index)
  const constName = entryConstName(index)

  if (entry.type === "http") {
    return `export type ${entryTypeName(index)}EffectClient = ${typeApplication(
      "EffectHttpApiClientTypes.ForApi",
      `typeof ${valueName}`
    )}
export type ${entryTypeName(index)}PromiseClient = ${typeApplication(
      "AwaitableClient",
      `${entryTypeName(index)}EffectClient`
    )}
${generateNamedEntryTypes(entry, index)}

const ${constName}EffectClient: ${entryTypeName(index)}EffectClient = await Effect.runPromise(
  EffectHttpApiClient.make(${valueName}, {
    baseUrl: ${JSON.stringify(typeof entry.apiPrefix === "string" ? entry.apiPrefix : defaultApiPrefix)}
  }).pipe(Effect.provide(FetchHttpClient.layer))
)
const ${constName}PromiseClient = makeHttpPromiseClient(
  ${valueName},
  ${constName}EffectClient
) as ${entryTypeName(index)}PromiseClient
`
  }

  return `export type ${entryTypeName(index)}EffectClient = ${typeApplication(
    "EffectRpcClientTypes.FromGroup",
    `typeof ${valueName}, EffectRpcClientError.RpcClientError`
  )}
export type ${entryTypeName(index)}PromiseClient = ${typeApplication(
    "AwaitableClient",
    `${entryTypeName(index)}EffectClient`
  )}
${generateNamedEntryTypes(entry, index)}

const ${constName}Scope = Scope.makeUnsafe()
const ${constName}EffectClient: ${entryTypeName(index)}EffectClient = await Effect.runPromise(
  EffectRpcClient.make(${valueName}).pipe(
    Effect.provide(EffectRpcClient.layerProtocolHttp({ url: ${JSON.stringify(entry.rpcPath)} })),
    Effect.provide(RpcSerialization.layerJson),
    Effect.provideService(Scope.Scope, ${constName}Scope),
    Effect.provide(FetchHttpClient.layer)
  )
)
const ${constName}PromiseClient = makeRpcPromiseClient(
  ${valueName},
  ${constName}EffectClient
) as ${entryTypeName(index)}PromiseClient
`
}

const generateNamedEntryTypes = (entry: ResolvedClientEntry, index: number): string => {
  const name = toPascalIdentifier(entry.name)
  if (!name) return ""
  return `export type ${name}EffectClient = ${entryTypeName(index)}EffectClient
export type ${name}PromiseClient = ${entryTypeName(index)}PromiseClient
export type ${name}Client = ${entryTypeName(index)}PromiseClient
export type ${name}Results = EntryResultMap<${name}Client>
export type ${name}Inputs = EntryInputMap<${name}Client>
export type ${name}Payloads = EntryPayloadMap<${name}Client>`
}

const generateCombinedType = (
  options: ResolvedPluginOptions,
  kind: "Effect" | "Promise"
): string => {
  if (options.entries.length === 1) {
    return `${entryTypeName(0)}${kind}Client`
  }
  return `{ readonly ${options.entries
    .map((entry, index) => `${entry.name}: ${entryTypeName(index)}${kind}Client`)
    .join("; readonly ")} }`
}
