import * as path from "node:path"
import type { ResolvedConfig } from "vite"
import { defaultDtsFallbackPath } from "../defaults"
import { isClientPathEnabled } from "../options"
import type { ResolvedPluginOptions } from "../options"
import { toRelativeTypeImport } from "../path-utils"

const stripTypeScriptExtension = (specifier: string): string =>
  specifier.replace(/\.(ts|tsx|mts|cts)$/, "")

export const generateVirtualClientDts = (
  options: ResolvedPluginOptions,
  config: ResolvedConfig,
  dtsPath = path.resolve(config.root, options.dts || defaultDtsFallbackPath)
): string => {
  if (isClientPathEnabled(options)) {
    const clientImport = stripTypeScriptExtension(
      toRelativeTypeImport(config, dtsPath, options.clientPath)
    )
    return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
declare module "vite-plugin-effect/client" {
  interface EffectClientConfig {
    readonly client: import("${clientImport}").EffectClient
    readonly defaultClient: import("${clientImport}").Client
  }
}

declare module ${JSON.stringify(options.virtualModuleId)} {
  export { client, effectClient, promiseClient } from "${clientImport}"
  export type * from "${clientImport}"
}
`
  }

  return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
declare module "vite-plugin-effect/client" {
  interface EffectClientConfig {
    readonly client: never
    readonly defaultClient: never
  }
}
`
}
