import * as path from "node:path"
import type { ResolvedConfig } from "vite"
import { defaultDtsFallbackPath } from "../defaults"
import { isClientPathEnabled } from "../options"
import type { ResolvedPluginOptions } from "../options"
import { toRelativeTypeImport } from "../path-utils"
import { typeApplication } from "./codegen-utils"
import { stripTypeScriptExtension } from "./schema-discovery"

export const generateVirtualClientDts = (
  options: ResolvedPluginOptions,
  config: ResolvedConfig,
  dtsPath = path.resolve(config.root, options.dts || defaultDtsFallbackPath)
): string => {
  if (isClientPathEnabled(options)) {
    const clientImport = stripTypeScriptExtension(
      toRelativeTypeImport(config, dtsPath, options.clientPath)
    )
    return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
declare module "vite-plugin-effect/client" {
  interface EffectClientConfig {
    readonly client: import("${clientImport}").EffectClient
    readonly defaultClient: import("${clientImport}").Client
  }
}
`
  }

  const entry = options.entries[0]
  if (!entry) {
    return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
declare module "vite-plugin-effect/client" {
  interface EffectClientConfig {
    readonly client: unknown
    readonly defaultClient: unknown
  }
}
`
  }

  const sharedImport = stripTypeScriptExtension(
    toRelativeTypeImport(config, dtsPath, entry.sharedPath)
  )
  const effectClientType =
    entry.type === "http"
      ? `import("effect/unstable/httpapi").HttpApiClient.ForApi<typeof import("${sharedImport}").${entry.exportName}>`
      : `import("effect/unstable/rpc").RpcClient.FromGroup<typeof import("${sharedImport}").${entry.exportName}>`
  const defaultClientType =
    options.clientKind === "effect"
      ? effectClientType
      : typeApplication(
          'import("vite-plugin-effect/client").AwaitableClient',
          effectClientType
        )

  return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
declare module "vite-plugin-effect/client" {
  interface EffectClientConfig {
    readonly client: ${effectClientType}
    readonly defaultClient: ${defaultClientType}
  }
}
`
}
