import * as path from "node:path"
import type { ResolvedConfig } from "vite"
import { isClientPathEnabled } from "../options"
import type { ResolvedPluginOptions } from "../options"

export const virtualClientTypes = `
import type { Effect, Stream } from "effect"

export type AwaitableClient<T> =
  T extends (...args: infer Args) => infer Return
    ? (...args: AwaitableClientArgs<Args>) => AwaitableClientReturn<Return>
    : T extends object
      ? { readonly [Key in keyof T]: AwaitableClient<T[Key]> }
      : T

export type AwaitableClientArgs<Args extends ReadonlyArray<unknown>> =
  Args extends [request: infer Request]
    ? [request: AwaitableClientRequest<Request>]
    : Args extends [request?: infer Request]
      ? [request?: AwaitableClientRequest<Request>]
      : Args

export type AwaitableClientRequest<Request> =
  Request extends object
    ? Exclude<keyof Request, "responseMode"> extends "payload"
      ? Request | Request extends { readonly payload: infer Payload } ? Payload : never
      : Request
    : Request

export type AwaitableClientReturn<T> =
  T extends Effect.Effect<infer Success, infer _Error, infer _Services>
    ? Promise<Success>
    : T extends Stream.Stream<infer _Success, infer _Error, infer _Services>
      ? T
      : T

export type ClientMethod = (...args: ReadonlyArray<never>) => never

export type MethodInput<Method> =
  Method extends (...args: infer Args) => infer _Return
    ? Args extends []
      ? void
      : Args[0]
    : never

export type MethodPayload<Input> =
  Input extends { readonly payload: infer Payload } ? Payload : Input

export type MethodPart<Input, Key extends PropertyKey> =
  Input extends { readonly [K in Key]?: infer Value } ? Value : never

export type MethodParams<Input> = MethodPart<Input, "params">

export type MethodQuery<Input> = MethodPart<Input, "query">

export type MethodHeaders<Input> = MethodPart<Input, "headers">

export type MethodReturn<Method> =
  Method extends (...args: infer _Args) => infer Return ? Return : never

export type MethodSuccess<Method> =
  MethodReturn<Method> extends Effect.Effect<infer Success, infer _Error, infer _Services>
    ? Success
    : Awaited<MethodReturn<Method>>

export type MethodError<Method> =
  MethodReturn<Method> extends Effect.Effect<infer _Success, infer Error, infer _Services>
    ? Error
    : never

export type MethodResult<Method> = MethodSuccess<Method>

export const effectClient: never
export const promiseClient: never
export const client: never
`

export const generateVirtualClientModule = (
  options: ResolvedPluginOptions,
  config: ResolvedConfig
): string => {
  if (!isClientPathEnabled(options)) {
    throw new Error("clientPath: false requires virtualModuleContent")
  }

  const clientPath = path.resolve(config.root, options.clientPath)
  return `// Auto-generated by vite-plugin-effect
export { client, effectClient, promiseClient } from ${JSON.stringify(clientPath)}
`
}

export const generateVirtualTypesModule = (): string => {
  return virtualClientTypes
}
