import * as path from "node:path"
import type { ResolvedConfig } from "vite"
import { isClientPathEnabled } from "../options"
import type { ResolvedPluginOptions } from "../options"

export const virtualClientTypes = `
import type { Effect, Stream } from "effect"

export type AwaitableClient<T> =
  T extends (...args: infer Args) => infer Return
    ? (...args: AwaitableClientArgs<Args>) => AwaitableClientReturn<Return>
    : T extends object
      ? { readonly [Key in keyof T]: AwaitableClient<T[Key]> }
      : T

export type AwaitableClientArgs<Args extends ReadonlyArray<unknown>> =
  Args extends [request: infer Request]
    ? [request: AwaitableClientRequest<Request>]
    : Args extends [request?: infer Request]
      ? [request?: AwaitableClientRequest<Request>]
      : Args

export type AwaitableClientRequest<Request> =
  Request extends object
    ? Exclude<keyof Request, "responseMode"> extends "payload"
      ? Request | Request extends { readonly payload: infer Payload } ? Payload : never
      : Request
    : Request

export type AwaitableClientReturn<T> =
  T extends Effect.Effect<infer Success, infer _Error, infer _Services>
    ? Promise<Success>
    : T extends Stream.Stream<infer _Success, infer _Error, infer _Services>
      ? T
      : T

export const effectClient: unknown
export const promiseClient: unknown
export const client: unknown
`

export const generateVirtualClientModule = (
  options: ResolvedPluginOptions,
  config: ResolvedConfig
): string => {
  if (options.virtualModuleContent) {
    return options.virtualModuleContent({
      entry: options.entries[0]!,
      entries: options.entries,
      clientKind: options.clientKind,
    })
  }

  if (!isClientPathEnabled(options)) {
    throw new Error("clientPath: false requires virtualModuleContent")
  }

  const clientPath = path.resolve(config.root, options.clientPath)
  return `// Auto-generated by vite-plugin-effect
export { client, effectClient, promiseClient } from ${JSON.stringify(clientPath)}
`
}

export const generateVirtualTypesModule = (): string => {
  return virtualClientTypes
}
