/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
import { HttpApi, HttpApiEndpoint, HttpApiGroup, HttpApiClient } from "effect/unstable/httpapi"
import { RpcClient, RpcClientError, RpcGroup, Rpc as EffectRpc, RpcSerialization } from "effect/unstable/rpc"
import { Effect, Schema, Scope } from "effect"
import { FetchHttpClient } from "effect/unstable/http"
import type { AwaitableClient, MethodError, MethodInput, MethodParams, MethodPayload, MethodSuccess } from "vite-plugin-effect/client"

const ApiValidationError = class ApiValidationError extends Schema.TaggedErrorClass<ApiValidationError>()("ApiValidationError", { "code": Schema.Literal("VALIDATION_FAILED"), "message": Schema.String, "field": Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])) }, { "httpApiStatus": 422 }) {}
const ApiNotFound = class ApiNotFound extends Schema.TaggedErrorClass<ApiNotFound>()("ApiNotFound", { "code": Schema.Literal("NOT_FOUND"), "message": Schema.String, "resource": Schema.String, "id": Schema.String }, { "httpApiStatus": 404 }) {}
const ApiConflictError = class ApiConflictError extends Schema.TaggedErrorClass<ApiConflictError>()("ApiConflictError", { "code": Schema.Literal("CONFLICT"), "message": Schema.String, "resource": Schema.String }, { "httpApiStatus": 409 }) {}
const Todo = Schema.Struct({ "id": Schema.Number, "title": Schema.String, "completed": Schema.Boolean })
const __schema0 = Schema.Struct({ "id": Schema.Number })
const TodoUpdate = Schema.Struct({ "title": Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])), "completed": Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Undefined])) })
const User = Schema.Struct({ "id": Schema.Number, "name": Schema.String, "email": Schema.String })
const UserUpdate = Schema.Struct({ "name": Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])), "email": Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])) })
const ApiError = Schema.Union([ApiNotFound, ApiValidationError, ApiConflictError])
const TodoStats = Schema.Struct({ "total": Schema.Number, "completed": Schema.Number, "open": Schema.Number })

export type ApiValidationError = Schema.Schema.Type<typeof ApiValidationError>
export type ApiNotFound = Schema.Schema.Type<typeof ApiNotFound>
export type ApiConflictError = Schema.Schema.Type<typeof ApiConflictError>
export type Todo = Schema.Schema.Type<typeof Todo>
export type TodoUpdate = Schema.Schema.Type<typeof TodoUpdate>
export type User = Schema.Schema.Type<typeof User>
export type UserUpdate = Schema.Schema.Type<typeof UserUpdate>
export type ApiError = Schema.Schema.Type<typeof ApiError>
export type TodoStats = Schema.Schema.Type<typeof TodoStats>

const __httpApi0 = HttpApi.make("MyApi").add(
  HttpApiGroup.make("todos").add(
    HttpApiEndpoint.make("GET")("getTodos", "/todos", { success: Schema.Array(Todo) }),
    HttpApiEndpoint.make("POST")("createTodo", "/todos", { payload: Schema.Struct({ "title": Schema.String }), success: Todo, error: ApiValidationError }),
    HttpApiEndpoint.make("DELETE")("deleteTodo", "/todos/:id", { params: __schema0, success: Todo, error: ApiNotFound }),
    HttpApiEndpoint.make("PATCH")("updateTodo", "/todos/:id", { params: __schema0, payload: TodoUpdate, success: Todo, error: Schema.Union([ApiNotFound, ApiValidationError]) })
  ),
  HttpApiGroup.make("users").add(
    HttpApiEndpoint.make("GET")("getUsers", "/users", { success: Schema.Array(User) }),
    HttpApiEndpoint.make("POST")("createUser", "/users", { payload: Schema.Struct({ "name": Schema.String, "email": Schema.String }), success: User, error: Schema.Union([ApiValidationError, ApiConflictError]) }),
    HttpApiEndpoint.make("DELETE")("deleteUser", "/users/:id", { params: __schema0, success: User, error: ApiNotFound }),
    HttpApiEndpoint.make("PATCH")("updateUser", "/users/:id", { params: __schema0, payload: UserUpdate, success: User, error: ApiError })
  )
)

const __effectClient0 = await Effect.runPromise(
  HttpApiClient.make(__httpApi0, { baseUrl: "/api" }).pipe(
    Effect.provide(FetchHttpClient.layer)
  )
)
const __rpcGroup1 = RpcGroup.make(
  EffectRpc.make("todoStats", { payload: Schema.Struct({ "completed": Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Undefined])) }), success: TodoStats, error: ApiError }),
  EffectRpc.make("toggleTodo", { payload: __schema0, success: Todo, error: ApiError }),
  EffectRpc.make("deleteTodo", { payload: __schema0, success: Todo, error: ApiError }),
  EffectRpc.make("updateTodo", { payload: Schema.Struct({ "id": Schema.Number, "title": Schema.String }), success: Todo, error: ApiError })
)

const __effectClient1Scope = Scope.makeUnsafe()
const __effectClient1 = await Effect.runPromise(
  RpcClient.make(__rpcGroup1).pipe(
    Effect.provide(RpcClient.layerProtocolHttp({ url: "/rpc" })),
    Effect.provide(RpcSerialization.layerJson),
    Effect.provideService(Scope.Scope, __effectClient1Scope),
    Effect.provide(FetchHttpClient.layer)
  )
)

const reservedRequestKeys = new Set<PropertyKey>(["payload", "params", "query", "headers", "responseMode"])

function normalizeRequest<Request>(request: Request | MethodPayload<Request>, hasArgument: boolean): Request {
  if (!hasArgument) {
    return undefined as Request
  }
  if (request === null || typeof request !== "object") {
    return { payload: request } as Request
  }
  for (const key of reservedRequestKeys) {
    if (key in request) return request as Request
  }
  return { payload: request } as Request
}

export type Entry0EffectClient = HttpApiClient.ForApi<typeof __httpApi0>
export type Entry0PromiseClient = AwaitableClient<Entry0EffectClient>
export type ApiEffectClient = Entry0EffectClient
export type ApiPromiseClient = Entry0PromiseClient
export type ApiClient = Entry0PromiseClient
export type Entry1EffectClient = RpcClient.FromGroup<typeof __rpcGroup1, RpcClientError.RpcClientError>
export type Entry1PromiseClient = AwaitableClient<Entry1EffectClient>
export type RpcEffectClient = Entry1EffectClient
export type RpcPromiseClient = Entry1PromiseClient
export type RpcClient = Entry1PromiseClient

export namespace Api {
  export namespace todos {
    export namespace getTodos {
      type Method = Entry0EffectClient["todos"]["getTodos"]
      export type Input = MethodInput<Method>
      export type Success = MethodSuccess<Method>
    }

    export namespace createTodo {
      type Method = Entry0EffectClient["todos"]["createTodo"]
      export type Input = MethodInput<Method>
      export type Payload = MethodPayload<Input>
      export type Success = MethodSuccess<Method>
      export type Error = MethodError<Method>
    }

    export namespace deleteTodo {
      type Method = Entry0EffectClient["todos"]["deleteTodo"]
      export type Input = MethodInput<Method>
      export type Params = MethodParams<Input>
      export type Success = MethodSuccess<Method>
      export type Error = MethodError<Method>
    }

    export namespace updateTodo {
      type Method = Entry0EffectClient["todos"]["updateTodo"]
      export type Input = MethodInput<Method>
      export type Params = MethodParams<Input>
      export type Payload = MethodPayload<Input>
      export type Success = MethodSuccess<Method>
      export type Error = MethodError<Method>
    }
  }

  export namespace users {
    export namespace getUsers {
      type Method = Entry0EffectClient["users"]["getUsers"]
      export type Input = MethodInput<Method>
      export type Success = MethodSuccess<Method>
    }

    export namespace createUser {
      type Method = Entry0EffectClient["users"]["createUser"]
      export type Input = MethodInput<Method>
      export type Payload = MethodPayload<Input>
      export type Success = MethodSuccess<Method>
      export type Error = MethodError<Method>
    }

    export namespace deleteUser {
      type Method = Entry0EffectClient["users"]["deleteUser"]
      export type Input = MethodInput<Method>
      export type Params = MethodParams<Input>
      export type Success = MethodSuccess<Method>
      export type Error = MethodError<Method>
    }

    export namespace updateUser {
      type Method = Entry0EffectClient["users"]["updateUser"]
      export type Input = MethodInput<Method>
      export type Params = MethodParams<Input>
      export type Payload = MethodPayload<Input>
      export type Success = MethodSuccess<Method>
      export type Error = MethodError<Method>
    }
  }
}
export namespace Rpc {
  export namespace todoStats {
    type Method = Entry1EffectClient["todoStats"]
    export type Input = MethodInput<Method>
    export type Payload = MethodPayload<Input>
    export type Success = MethodSuccess<Method>
    export type Error = MethodError<Method>
  }

  export namespace toggleTodo {
    type Method = Entry1EffectClient["toggleTodo"]
    export type Input = MethodInput<Method>
    export type Payload = MethodPayload<Input>
    export type Success = MethodSuccess<Method>
    export type Error = MethodError<Method>
  }

  export namespace deleteTodo {
    type Method = Entry1EffectClient["deleteTodo"]
    export type Input = MethodInput<Method>
    export type Payload = MethodPayload<Input>
    export type Success = MethodSuccess<Method>
    export type Error = MethodError<Method>
  }

  export namespace updateTodo {
    type Method = Entry1EffectClient["updateTodo"]
    export type Input = MethodInput<Method>
    export type Payload = MethodPayload<Input>
    export type Success = MethodSuccess<Method>
    export type Error = MethodError<Method>
  }
}

export type EffectClient = { readonly api: Entry0EffectClient; readonly rpc: Entry1EffectClient }
export type PromiseClient = { readonly api: Entry0PromiseClient; readonly rpc: Entry1PromiseClient }
export type Client = PromiseClient

const __promiseClient0: Entry0PromiseClient = {
  todos: {
    getTodos: (...args) => Effect.runPromise(__effectClient0.todos.getTodos(normalizeRequest<MethodInput<Entry0EffectClient["todos"]["getTodos"]>>(args[0], args.length > 0))),
    createTodo: (...args) => Effect.runPromise(__effectClient0.todos.createTodo(normalizeRequest<MethodInput<Entry0EffectClient["todos"]["createTodo"]>>(args[0], args.length > 0))),
    deleteTodo: (...args) => Effect.runPromise(__effectClient0.todos.deleteTodo(normalizeRequest<MethodInput<Entry0EffectClient["todos"]["deleteTodo"]>>(args[0], args.length > 0))),
    updateTodo: (...args) => Effect.runPromise(__effectClient0.todos.updateTodo(normalizeRequest<MethodInput<Entry0EffectClient["todos"]["updateTodo"]>>(args[0], args.length > 0)))
  },
  users: {
    getUsers: (...args) => Effect.runPromise(__effectClient0.users.getUsers(normalizeRequest<MethodInput<Entry0EffectClient["users"]["getUsers"]>>(args[0], args.length > 0))),
    createUser: (...args) => Effect.runPromise(__effectClient0.users.createUser(normalizeRequest<MethodInput<Entry0EffectClient["users"]["createUser"]>>(args[0], args.length > 0))),
    deleteUser: (...args) => Effect.runPromise(__effectClient0.users.deleteUser(normalizeRequest<MethodInput<Entry0EffectClient["users"]["deleteUser"]>>(args[0], args.length > 0))),
    updateUser: (...args) => Effect.runPromise(__effectClient0.users.updateUser(normalizeRequest<MethodInput<Entry0EffectClient["users"]["updateUser"]>>(args[0], args.length > 0)))
  }
}
const __promiseClient1: Entry1PromiseClient = {
  todoStats: (payload, options) => Effect.runPromise(__effectClient1.todoStats(payload, options)),
  toggleTodo: (payload, options) => Effect.runPromise(__effectClient1.toggleTodo(payload, options)),
  deleteTodo: (payload, options) => Effect.runPromise(__effectClient1.deleteTodo(payload, options)),
  updateTodo: (payload, options) => Effect.runPromise(__effectClient1.updateTodo(payload, options))
}

export const effectClient: EffectClient = { api: __effectClient0, rpc: __effectClient1 }
export const promiseClient: PromiseClient = { api: __promiseClient0, rpc: __promiseClient1 }
export const client: Client = { api: __promiseClient0, rpc: __promiseClient1 }