/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
import { Effect, Scope } from "effect"
import { FetchHttpClient } from "effect/unstable/http"
import { HttpApi, HttpApiClient as EffectHttpApiClient } from "effect/unstable/httpapi"
import type { HttpApiClient as EffectHttpApiClientTypes } from "effect/unstable/httpapi"
import { RpcClient as EffectRpcClient, RpcSerialization } from "effect/unstable/rpc"
import type { RpcClient as EffectRpcClientTypes, RpcClientError as EffectRpcClientError } from "effect/unstable/rpc"
import type { AwaitableClient, ClientMethod, MethodInput, MethodPayload, MethodResult } from "vite-plugin-effect/client"
import { MyApi as __effectEntry0 } from "../server/shared"
import { TodoRpc as __effectEntry1 } from "../server/shared"

const reservedRequestKeys = new Set(["payload", "params", "query", "headers", "responseMode"])

function normalizeRequest(request: unknown): unknown {
  if (request === undefined || request === null || typeof request !== "object") {
    return { payload: request }
  }
  for (const key of reservedRequestKeys) {
    if (key in request) return request
  }
  return { payload: request }
}


function makeHttpPromiseClient(
  api: HttpApi.AnyWithProps,
  effectClientValue: unknown
): unknown {
  const promiseClientValue: Record<PropertyKey, any> = {}
  HttpApi.reflect(api, {
    onGroup({ group }) {
      if (!group.topLevel) {
        promiseClientValue[group.identifier] = {}
      }
    },
    onEndpoint({ group, endpoint }) {
      const effectContainer = group.topLevel
        ? effectClientValue as Record<PropertyKey, any>
        : (effectClientValue as Record<PropertyKey, any>)[group.identifier]
      const promiseContainer = group.topLevel
        ? promiseClientValue
        : promiseClientValue[group.identifier]
      promiseContainer[endpoint.name] = function(request: unknown) {
        return Effect.runPromise(effectContainer[endpoint.name](normalizeRequest(request)))
      }
    },
  })
  return promiseClientValue
}



function makeRpcPromiseClient(
  group: { readonly requests: ReadonlyMap<string, unknown> },
  effectClientValue: unknown
): unknown {
  const promiseClientValue: Record<string, unknown> = {}
  for (const tag of group.requests.keys()) {
    promiseClientValue[tag] = function(payload: unknown, options?: unknown) {
      const result = (effectClientValue as Record<string, any>)[tag](payload, options)
      return Effect.isEffect(result)
        ? Effect.runPromise(result as Effect.Effect<unknown, unknown, never>)
        : result
    }
  }
  return promiseClientValue
}


export type Entry0EffectClient = EffectHttpApiClientTypes.ForApi<typeof __effectEntry0>
export type Entry0PromiseClient = AwaitableClient<Entry0EffectClient>
export type ApiEffectClient = Entry0EffectClient
export type ApiPromiseClient = Entry0PromiseClient
export type ApiClient = Entry0PromiseClient
export type ApiResults = EntryResultMap<ApiClient>
export type ApiInputs = EntryInputMap<ApiClient>
export type ApiPayloads = EntryPayloadMap<ApiClient>

const __effectClient0EffectClient: Entry0EffectClient = await Effect.runPromise(
  EffectHttpApiClient.make(__effectEntry0, {
    baseUrl: "/api"
  }).pipe(Effect.provide(FetchHttpClient.layer))
)
const __effectClient0PromiseClient = makeHttpPromiseClient(
  __effectEntry0,
  __effectClient0EffectClient
) as Entry0PromiseClient

export type Entry1EffectClient = EffectRpcClientTypes.FromGroup<typeof __effectEntry1, EffectRpcClientError.RpcClientError>
export type Entry1PromiseClient = AwaitableClient<Entry1EffectClient>
export type RpcEffectClient = Entry1EffectClient
export type RpcPromiseClient = Entry1PromiseClient
export type RpcClient = Entry1PromiseClient
export type RpcResults = EntryResultMap<RpcClient>
export type RpcInputs = EntryInputMap<RpcClient>
export type RpcPayloads = EntryPayloadMap<RpcClient>

const __effectClient1Scope = Scope.makeUnsafe()
const __effectClient1EffectClient: Entry1EffectClient = await Effect.runPromise(
  EffectRpcClient.make(__effectEntry1).pipe(
    Effect.provide(EffectRpcClient.layerProtocolHttp({ url: "/rpc" })),
    Effect.provide(RpcSerialization.layerJson),
    Effect.provideService(Scope.Scope, __effectClient1Scope),
    Effect.provide(FetchHttpClient.layer)
  )
)
const __effectClient1PromiseClient = makeRpcPromiseClient(
  __effectEntry1,
  __effectClient1EffectClient
) as Entry1PromiseClient


export type EffectClient = { readonly api: Entry0EffectClient; readonly rpc: Entry1EffectClient }
export type PromiseClient = { readonly api: Entry0PromiseClient; readonly rpc: Entry1PromiseClient }
export type Client = PromiseClient

export type SchemaType<SchemaValue> = SchemaValue extends { readonly Type: infer Type } ? Type : never
export type Todo = SchemaType<typeof import("../server/shared").Todo>
export type User = SchemaType<typeof import("../server/shared").User>
export type TodoUpdate = SchemaType<typeof import("../server/shared").TodoUpdate>
export type UserUpdate = SchemaType<typeof import("../server/shared").UserUpdate>
export type TodoStats = SchemaType<typeof import("../server/shared").TodoStats>

export type EntryResultMap<Entry> = {
  readonly [Key in keyof Entry]: Entry[Key] extends ClientMethod
    ? MethodResult<Entry[Key]>
    : Entry[Key] extends object
      ? {
          readonly [Endpoint in keyof Entry[Key]]: Entry[Key][Endpoint] extends ClientMethod
            ? MethodResult<Entry[Key][Endpoint]>
            : never
        }
      : never
}
export type EntryInputMap<Entry> = {
  readonly [Key in keyof Entry]: Entry[Key] extends ClientMethod
    ? MethodInput<Entry[Key]>
    : Entry[Key] extends object
      ? {
          readonly [Endpoint in keyof Entry[Key]]: Entry[Key][Endpoint] extends ClientMethod
            ? MethodInput<Entry[Key][Endpoint]>
            : never
        }
      : never
}
export type EntryPayloadMap<Entry> = {
  readonly [Key in keyof Entry]: Entry[Key] extends ClientMethod
    ? MethodPayload<MethodInput<Entry[Key]>>
    : Entry[Key] extends object
      ? {
          readonly [Endpoint in keyof Entry[Key]]: Entry[Key][Endpoint] extends ClientMethod
            ? MethodPayload<MethodInput<Entry[Key][Endpoint]>>
            : never
        }
      : never
}
export type ClientResults = EntryResultMap<Client>
export type ClientInputs = EntryInputMap<Client>
export type ClientPayloads = EntryPayloadMap<Client>

export type ClientGroups = {
  readonly [Key in keyof Client as Client[Key] extends ClientMethod ? never : Key]: Client[Key]
}
export type ClientGroupName = keyof ClientGroups
export type ClientGroup<Name extends ClientGroupName> = ClientGroups[Name]
export type ClientTopLevelEndpointName = {
  readonly [Key in keyof Client]: Client[Key] extends ClientMethod ? Key : never
}[keyof Client]
export type ClientEndpointName<Group extends ClientGroupName> = keyof ClientGroups[Group]
export type ClientEndpoint<Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>> = ClientGroups[Group][Endpoint] extends ClientMethod ? ClientGroups[Group][Endpoint] : never
export type TopLevelEndpoint<Name extends ClientTopLevelEndpointName> = Client[Name] extends ClientMethod ? Client[Name] : never
export type EndpointInput<Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>> = MethodInput<ClientEndpoint<Group, Endpoint>>
export type EndpointPayload<Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>> = MethodPayload<EndpointInput<Group, Endpoint>>
export type EndpointResult<Group extends ClientGroupName, Endpoint extends ClientEndpointName<Group>> = MethodResult<ClientEndpoint<Group, Endpoint>>

export const effectClient: EffectClient = { api: __effectClient0EffectClient, rpc: __effectClient1EffectClient }
export const promiseClient: PromiseClient = { api: __effectClient0PromiseClient, rpc: __effectClient1PromiseClient }
export const client: Client = promiseClient
