import * as Schema from "effect/Schema"
import { collectSchemas, getSchemaIdentifier } from "./schema-reflector"
import type { SchemaRegistry } from "./schema-reflector"
import type { HttpApiInfo, HttpEndpointInfo } from "./http-reflector"
import type { RpcGroupInfo, RpcInfo } from "./rpc-reflector"

export interface ClientGeneratorOptions {
  readonly clientKind: "effect" | "promise"
  readonly baseUrl?: string
  readonly rpcPath?: string
  readonly contractVarName?: string
}

export function generateHttpClient(apiInfo: HttpApiInfo, options: ClientGeneratorOptions): string {
  const schemaRegistry = collectSchemas(apiInfo.schemas, apiInfo.schemaNames)
  const schemaDecls = schemaRegistry.declarations.join("\n")
  const schemaTypes = schemaRegistry.typeAliases.join("\n")

  const apiDecl = generateHttpApiDeclaration(apiInfo, schemaRegistry)

  const effectDecl = generateEffectHttpClient(apiInfo, options.baseUrl)
  const promiseDecl = generatePromiseHttpClient(apiInfo, options.baseUrl)

  const clientDecl = options.clientKind === "effect"
    ? `${effectDecl}\n${promiseDecl}\nexport const client = effectClient`
    : `${effectDecl}\n${promiseDecl}\nexport const client = promiseClient`

  return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
import { Schema, Effect } from "effect"
import { FetchHttpClient } from "effect/unstable/http"
import { HttpApi, HttpApiEndpoint, HttpApiGroup, HttpApiClient } from "effect/unstable/httpapi"
import type { AwaitableClient, MethodInput, MethodPayload } from "vite-plugin-effect/client"

${schemaDecls}

${schemaTypes}

${apiDecl}

${httpNormalizeRequestHelper()}

${clientDecl}
`
}

export function generateRpcClient(rpcInfo: RpcGroupInfo, options: ClientGeneratorOptions): string {
  const schemaRegistry = collectSchemas(rpcInfo.schemas, rpcInfo.schemaNames)
  const schemaDecls = schemaRegistry.declarations.join("\n")
  const schemaTypes = schemaRegistry.typeAliases.join("\n")

  const rpcGroupDecl = generateRpcGroupDeclaration(rpcInfo, schemaRegistry)

  const effectDecl = generateEffectRpcClient(rpcInfo, options.rpcPath)
  const promiseDecl = generatePromiseRpcClient(rpcInfo, options.rpcPath)

  const clientDecl = options.clientKind === "effect"
    ? `${effectDecl}\n${promiseDecl}\nexport const client = effectClient`
    : `${effectDecl}\n${promiseDecl}\nexport const client = promiseClient`

  return `/* eslint-disable */
// Auto-generated by vite-plugin-effect. Do not edit manually.
import { Schema, Effect, Scope } from "effect"
import { FetchHttpClient } from "effect/unstable/http"
import { RpcClient, RpcClientError, RpcGroup, Rpc as EffectRpc, RpcSerialization } from "effect/unstable/rpc"
import type { AwaitableClient } from "vite-plugin-effect/client"

${schemaDecls}

${schemaTypes}

${rpcGroupDecl}

${clientDecl}
`
}

export function generateHttpClientBody(
  apiInfo: HttpApiInfo,
  options: Pick<ClientGeneratorOptions, "baseUrl" | "contractVarName">,
  clientVarName?: string,
  schemaRegistry?: SchemaRegistry
): string {
  const registry = schemaRegistry ?? collectSchemas(apiInfo.schemas, apiInfo.schemaNames)

  const apiVarName = options.contractVarName ?? apiInfo.identifier
  const apiDecl = generateHttpApiDeclaration(apiInfo, registry, apiVarName)

  const urlStr = options.baseUrl ? `"${options.baseUrl}"` : "undefined"
  const varName = clientVarName ?? "client"
  const clientVar = `const ${varName} = await Effect.runPromise(\n  HttpApiClient.make(${apiVarName}, { baseUrl: ${urlStr} }).pipe(\n    Effect.provide(FetchHttpClient.layer)\n  )\n)`

  if (schemaRegistry) {
    return `${apiDecl}\n\n${clientVar}`
  }
  return `${registry.declarations.join("\n")}\n\n${registry.typeAliases.join("\n")}\n\n${apiDecl}\n\n${clientVar}`
}

export function generateRpcClientBody(
  rpcInfo: RpcGroupInfo,
  options: Pick<ClientGeneratorOptions, "rpcPath" | "contractVarName">,
  clientVarName?: string,
  schemaRegistry?: SchemaRegistry
): string {
  const registry = schemaRegistry ?? collectSchemas(rpcInfo.schemas, rpcInfo.schemaNames)

  const rpcGroupVarName = options.contractVarName ?? "rpcGroup"
  const rpcGroupDecl = generateRpcGroupDeclaration(rpcInfo, registry, rpcGroupVarName)

  const pathStr = options.rpcPath ? `"${options.rpcPath}"` : '"/rpc"'
  const varName = clientVarName ?? "client"
  const clientVar = `const ${varName}Scope = Scope.makeUnsafe()\nconst ${varName} = await Effect.runPromise(\n  RpcClient.make(${rpcGroupVarName}).pipe(\n    Effect.provide(RpcClient.layerProtocolHttp({ url: ${pathStr} })),\n    Effect.provide(RpcSerialization.layerJson),\n    Effect.provideService(Scope.Scope, ${varName}Scope),\n    Effect.provide(FetchHttpClient.layer)\n  )\n)`

  if (schemaRegistry) {
    return `${rpcGroupDecl}\n\n${clientVar}`
  }
  return `${registry.declarations.join("\n")}\n\n${registry.typeAliases.join("\n")}\n\n${rpcGroupDecl}\n\n${clientVar}`
}

function generateHttpApiDeclaration(
  apiInfo: HttpApiInfo,
  schemaRegistry: SchemaRegistry,
  variableName = apiInfo.identifier
): string {
  const groupEndpoints = groupBy(apiInfo.endpoints, ep => ep.groupIdentifier)

  const groupDecls = Object.entries(groupEndpoints).map(([groupId, endpoints]) => {
    const endpointDecls = endpoints.map(ep => generateEndpointDeclaration(ep, schemaRegistry)).join(",\n    ")
    const options = endpoints.some((endpoint) => endpoint.groupTopLevel) ? ", { topLevel: true }" : ""
    return `HttpApiGroup.make("${groupId}"${options}).add(\n    ${endpointDecls}\n  )`
  }).join(",\n  ")

  return `const ${variableName} = HttpApi.make("${apiInfo.identifier}").add(\n  ${groupDecls}\n)`
}

function generateEndpointDeclaration(ep: HttpEndpointInfo, schemaRegistry: SchemaRegistry): string {
  const args: Array<string> = [
    `"${ep.name}"`,
    `"${ep.path}"`
  ]

  const options: Record<string, string> = {}

  if (ep.params) {
    options.params = getSchemaRefOrInline(ep.params, schemaRegistry)
  }
  if (ep.query) {
    options.query = getSchemaRefOrInline(ep.query, schemaRegistry)
  }
  if (ep.payload) {
    options.payload = getSchemaRefOrInline(ep.payload, schemaRegistry)
  }
  if (ep.headers) {
    options.headers = getSchemaRefOrInline(ep.headers, schemaRegistry)
  }
  if (ep.success) {
    options.success = getSchemaRefOrInline(ep.success, schemaRegistry)
  }
  if (ep.error) {
    options.error = getSchemaRefOrInline(ep.error, schemaRegistry)
  }

  const optionsStr = Object.entries(options)
    .map(([key, value]) => `${key}: ${value}`)
    .join(", ")

  if (optionsStr) {
    args.push(`{ ${optionsStr} }`)
  }

  return `HttpApiEndpoint.make("${ep.method}")(${args.join(", ")})`
}

function generateRpcGroupDeclaration(
  rpcInfo: RpcGroupInfo,
  schemaRegistry: SchemaRegistry,
  variableName = "rpcGroup"
): string {
  const rpcDecls = rpcInfo.rpcs.map(rpc => {
    const options: Record<string, string> = {}
    if (rpc.payload) {
      options.payload = getSchemaRefOrInline(rpc.payload, schemaRegistry)
    }
    if (rpc.success) {
      options.success = getSchemaRefOrInline(rpc.success, schemaRegistry)
    }
    if (rpc.error) {
      options.error = getSchemaRefOrInline(rpc.error, schemaRegistry)
    }

    const optionsStr = Object.entries(options)
      .map(([key, value]) => `${key}: ${value}`)
      .join(", ")

    return `EffectRpc.make("${rpc.tag}"${optionsStr ? `, { ${optionsStr} }` : ""})`
  }).join(",\n  ")

  return `const ${variableName} = RpcGroup.make(\n  ${rpcDecls}\n)`
}

function getSchemaRefOrInline(schema: Schema.Top, schemaRegistry?: SchemaRegistry): string {
  const expression = schemaRegistry?.getExpression(schema)
  if (expression) return expression

  const id = schemaRegistry?.getIdentifier(schema) ?? getSchemaIdentifier(schema)
  // If it's a built-in schema or doesn't have a meaningful identifier, inline it
  if (["String", "Number", "Boolean", "Void", "Never", "Any", "Unknown", "Undefined"].includes(id)) {
    return `Schema.${id}`
  }
  return id
}

function generateEffectHttpClient(apiInfo: HttpApiInfo, baseUrl?: string): string {
  const urlStr = baseUrl ? `"${baseUrl}"` : "undefined"
  return `export type EffectClient = HttpApiClient.ForApi<typeof ${apiInfo.identifier}>\nexport const effectClient: EffectClient = await Effect.runPromise(\n  HttpApiClient.make(${apiInfo.identifier}, { baseUrl: ${urlStr} }).pipe(\n    Effect.provide(FetchHttpClient.layer)\n  )\n)\n`
}

function generatePromiseHttpClient(apiInfo: HttpApiInfo, baseUrl?: string): string {
  void baseUrl
  return `export type PromiseClient = AwaitableClient<EffectClient>\nexport const promiseClient: PromiseClient = ${generateHttpPromiseClientObject("EffectClient", "effectClient", apiInfo.endpoints)}\n`
}

function generateEffectRpcClient(rpcInfo: RpcGroupInfo, rpcPath?: string): string {
  void rpcInfo
  const pathStr = rpcPath ? `"${rpcPath}"` : '"/rpc"'
  return `export type EffectClient = RpcClient.FromGroup<typeof rpcGroup, RpcClientError.RpcClientError>\nconst effectClientScope = Scope.makeUnsafe()\nexport const effectClient: EffectClient = await Effect.runPromise(\n  RpcClient.make(rpcGroup).pipe(\n    Effect.provide(RpcClient.layerProtocolHttp({ url: ${pathStr} })),\n    Effect.provide(RpcSerialization.layerJson),\n    Effect.provideService(Scope.Scope, effectClientScope),\n    Effect.provide(FetchHttpClient.layer)\n  )\n)\n`
}

function generatePromiseRpcClient(_rpcInfo: RpcGroupInfo, rpcPath?: string): string {
  void rpcPath
  return `export type PromiseClient = AwaitableClient<EffectClient>\nexport const promiseClient: PromiseClient = ${generateRpcPromiseClientObject("effectClient", _rpcInfo.rpcs)}\n`
}

function httpNormalizeRequestHelper(): string {
  return `const reservedRequestKeys = new Set<PropertyKey>(["payload", "params", "query", "headers", "responseMode"])

function normalizeRequest<Request>(request: Request | MethodPayload<Request>, hasArgument: boolean): Request {
  if (!hasArgument) {
    return undefined as Request
  }
  if (request === null || typeof request !== "object") {
    return { payload: request } as Request
  }
  for (const key of reservedRequestKeys) {
    if (key in request) return request as Request
  }
  return { payload: request } as Request
}`
}

function groupBy<T, K extends string>(arr: ReadonlyArray<T>, keyFn: (item: T) => K): Record<K, Array<T>> {
  const result = {} as Record<K, Array<T>>
  for (const item of arr) {
    const key = keyFn(item)
    if (!result[key]) {
      result[key] = []
    }
    result[key].push(item)
  }
  return result
}

function generateHttpPromiseClientObject(
  effectClientTypeName: string,
  effectVarName: string,
  endpoints: ReadonlyArray<HttpEndpointInfo>
): string {
  const topLevelMethods = endpoints.filter((endpoint) => endpoint.groupTopLevel)
  const groupedMethods = groupBy(endpoints.filter((endpoint) => !endpoint.groupTopLevel), (endpoint) => endpoint.groupIdentifier)
  const entries: Array<string> = []

  for (const endpoint of topLevelMethods) {
    entries.push(generateHttpPromiseEndpointProperty(effectClientTypeName, effectVarName, endpoint))
  }

  for (const [groupIdentifier, groupEndpoints] of Object.entries(groupedMethods)) {
    const groupAccess = accessProperty(effectVarName, groupIdentifier)
    const methods = groupEndpoints
      .map((endpoint) => generateHttpPromiseEndpointProperty(effectClientTypeName, groupAccess, endpoint))
      .join(",\n    ")
    entries.push(`${propertyKey(groupIdentifier)}: {\n    ${methods}\n  }`)
  }

  return `{\n  ${entries.join(",\n  ")}\n}`
}

function generateHttpPromiseEndpointProperty(
  effectClientTypeName: string,
  effectContainer: string,
  endpoint: HttpEndpointInfo
): string {
  const methodType = endpoint.groupTopLevel
    ? `${effectClientTypeName}[${JSON.stringify(endpoint.name)}]`
    : `${effectClientTypeName}[${JSON.stringify(endpoint.groupIdentifier)}][${JSON.stringify(endpoint.name)}]`
  const effectMethod = accessProperty(effectContainer, endpoint.name)
  return `${propertyKey(endpoint.name)}: (...args) => Effect.runPromise(${effectMethod}(normalizeRequest<MethodInput<${methodType}>>(args[0], args.length > 0)))`
}

function generateRpcPromiseClientObject(
  effectVarName: string,
  rpcs: ReadonlyArray<RpcInfo>
): string {
  const entries = rpcs
    .map((rpc) => {
      const effectMethod = accessProperty(effectVarName, rpc.tag)
      return `${propertyKey(rpc.tag)}: (payload, options) => Effect.runPromise(${effectMethod}(payload, options))`
    })
    .join(",\n  ")
  return `{\n  ${entries}\n}`
}

function accessProperty(base: string, key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? `${base}.${key}` : `${base}[${JSON.stringify(key)}]`
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name)
}
