import * as fs from "node:fs/promises"
import * as path from "node:path"
import type { ResolvedConfig } from "vite"
import type { ResolvedClientEntry, ResolvedPluginOptions } from "./options"
import { isProductionServerEnabled } from "./options"
import type { SsrStrategy } from "./ssr/index.ts"

interface SerializableEntry {
  readonly type: "http" | "rpc"
  readonly apiPrefix: string | SerializableRegExp
  readonly rpcPath: string
}

interface SerializableRegExp {
  readonly regexp: {
    readonly source: string
    readonly flags: string
  }
}

export const writeProductionServerRuntime = async (input: {
  readonly config: ResolvedConfig
  readonly options: ResolvedPluginOptions
  readonly serverOutDir: string
  readonly builtServerEntryFileName: string
  readonly ssrStrategy: SsrStrategy
}): Promise<void> => {
  if (!isProductionServerEnabled(input.options)) return

  const runtimeEntryPath = path.resolve(input.serverOutDir, input.options.productionServer.entry)
  const builtServerEntryPath = path.resolve(input.serverOutDir, input.builtServerEntryFileName)
  const staticRootPath = path.resolve(input.config.root, input.config.build.outDir)
  const content = generateProductionServerRuntime({
    runtimeEntryPath,
    builtServerEntryPath,
    staticRootPath,
    serverOutDir: input.serverOutDir,
    options: input.options,
    ssrStrategy: input.ssrStrategy,
  })

  await fs.mkdir(path.dirname(runtimeEntryPath), { recursive: true })
  await fs.writeFile(runtimeEntryPath, content)
}

export const generateProductionServerRuntime = (input: {
  readonly runtimeEntryPath: string
  readonly builtServerEntryPath: string
  readonly staticRootPath: string
  readonly serverOutDir: string
  readonly options: ResolvedPluginOptions
  readonly ssrStrategy: SsrStrategy
}): string => {
  if (!isProductionServerEnabled(input.options)) {
    throw new Error("productionServer options are required to generate runtime code")
  }

  const productionServer = input.options.productionServer
  const builtServerEntry = toRelativeUrl(input.runtimeEntryPath, input.builtServerEntryPath)
  const staticRoot = toRelativeUrl(input.runtimeEntryPath, input.staticRootPath, { directory: true })
  const entries = input.options.entries.map(serializeEntry)

  const ssrEntryUrl = input.ssrStrategy.getRuntimeEntryUrl(input.options, input.serverOutDir)
  const ssrConfig = ssrEntryUrl
    ? { ssrEntryUrl }
    : null

  if (productionServer.platform === "cloudflare") {
    return generateCloudflareRuntime({
      builtServerEntry,
      entries,
      serverExports: input.options.serverExports,
    })
  }

  return generateNodeRuntime({
    builtServerEntry,
    staticRoot,
    entries,
    serverExports: input.options.serverExports,
    productionServer,
    ssrConfig,
  })
}

const generateNodeRuntime = (input: {
  readonly builtServerEntry: string
  readonly staticRoot: string
  readonly entries: ReadonlyArray<SerializableEntry>
  readonly serverExports: ReadonlyArray<string>
  readonly productionServer: ResolvedPluginOptions["productionServer"] & object
  readonly ssrConfig: { ssrEntryUrl: string } | null
}): string => {
  return `// Auto-generated by vite-plugin-effect. Do not edit manually.
import { startProductionServer } from "./production-runtime.js"

const serverEntryUrl = new URL(${JSON.stringify(input.builtServerEntry)}, import.meta.url).href
const staticRoot = new URL(${JSON.stringify(input.staticRoot)}, import.meta.url).pathname
${input.ssrConfig ? `const ssrEntryUrl = ${input.ssrConfig.ssrEntryUrl}` : ""}

startProductionServer({
  serverEntryUrl,
  staticRoot,
  serverExports: ${JSON.stringify(input.serverExports, null, 2)},
  entries: ${JSON.stringify(input.entries, null, 2)},
  defaultHost: ${JSON.stringify(input.productionServer.host)},
  defaultPort: ${JSON.stringify(input.productionServer.port)},
  spaFallback: ${JSON.stringify(input.productionServer.spaFallback)},
  ${input.ssrConfig ? "ssrEntryUrl," : ""}
})
`
}

const generateCloudflareRuntime = (input: {
  readonly builtServerEntry: string
  readonly entries: ReadonlyArray<SerializableEntry>
  readonly serverExports: ReadonlyArray<string>
}): string => {
  return `// Auto-generated by vite-plugin-effect. Do not edit manually.
import { createCloudflareHandler } from "./cloudflare-runtime.js"
import * as serverModule from ${JSON.stringify(input.builtServerEntry)}

const handler = createCloudflareHandler({
  serverModule,
  staticRoot: "",
  serverExports: ${JSON.stringify(input.serverExports, null, 2)},
  entries: ${JSON.stringify(input.entries, null, 2)},
  defaultHost: "0.0.0.0",
  defaultPort: 8787,
  spaFallback: false,
  platform: "cloudflare",
})

export default {
  async fetch(request, env, ctx) {
    return handler(request, env, ctx)
  }
}
`
}

const serializeEntry = (entry: ResolvedClientEntry): SerializableEntry => ({
  type: entry.type,
  apiPrefix: serializeApiPrefix(entry.apiPrefix),
  rpcPath: entry.rpcPath,
})

const serializeApiPrefix = (apiPrefix: string | RegExp): string | SerializableRegExp => {
  if (typeof apiPrefix === "string") return apiPrefix
  return {
    regexp: {
      source: apiPrefix.source,
      flags: apiPrefix.flags.replace(/[gy]/g, ""),
    },
  }
}

const toRelativeUrl = (
  fromFile: string,
  toPath: string,
  options: { readonly directory?: boolean } = {}
): string => {
  let relativePath = path.relative(path.dirname(fromFile), toPath).replace(/\\/g, "/")
  if (!relativePath.startsWith(".")) {
    relativePath = `./${relativePath}`
  }
  if (options.directory === true && !relativePath.endsWith("/")) {
    relativePath = `${relativePath}/`
  }
  return relativePath
}
